### ISSUE TITLE
Error in DD - BaseInt : non-conformable arrays

### ISSUE THREAD

**Issue by Steven-ZWQ** [HDTian/DRMR#1]
I met a bug when I used the piecewise linear method with the doubly-ranked stratification. The bug disappeared when I used the piecewise linear method with the residual stratification.

**cutting_values<-(RES$DRres$mean[-1] + head( RES$DRres$mean,-1) )/2**
**smooth_res<-Smooth(RES,Norder=1,baseline=0,Knots=cutting_values)**

####the doubly-ranked stratification
The exposure range used:  0.452 2.35 
The internal knots are:  0.6835565 0.7519223 0.8227002 0.9228355  (Empty means no internal knots used) 
Random-effect is considered for smoothing and the actual random effect squared value is:  1 
0.452 2.35 0 
The actual basline value used:  
Error in DD - BaseInt : non-conformable arrays

####the residual stratification
The exposure range used:  -0.370359 1.548157 
The internal knots are:  -0.1347517 -0.05504739 0.02176186 0.1444838  (Empty means no internal knots used) 
Random-effect is considered for smoothing and the actual random effect squared value is:  1 
-0.370359 1.548157 0 
The actual basline value used: -0.001635231

**Comment by HDTian** [comment]
Hi,
This error occurs when you use a baseline value outside the exposure range. In this example using doubly-ranked stratification, the exposure range is (0.452,2.35), which does not cover 0.
You can either use the argument _baseline=NA_ (the default setting), or consider _baseline=any value inside (0.452,2.35)_

I will update the R script later, so any improper baseline value proposed will be alerted to prevent this error.
