### ISSUE TITLE
Error in rma(yi = est, sei = se, mods = cbind(mean), data = metadat) :    没有"rma"这个函数

### ISSUE THREAD

**Issue by 1297069621** [HDTian/DRMR#2]
install.packages("devtools")
library(DRMR)
dat<-getDat( IVtype='cont', ZXmodel='C',XYmodel='2' )
rdat<-Stratify(dat) 
RES<-getSummaryInf(rdat)
head(RES$DRres)
smooth_res<-Smooth(RES,Norder=3) #RES is the result returned by getSummaryInf()

Error in rma(yi = est, sei = se, mods = cbind(mean), data = metadat) : 
  没有"rma"这个函数

**Comment by HDTian** [comment]
Hi, please check if the package metafor was installed; try library(metafor) 
Once metafor is installed, rma should work

**Comment by 1297069621** [comment]
thank you! But a new question occurred.  Baseline=NA also not work.

> smooth_res<-Smooth(RES,Norder=3) #RES is the result returned by getSummaryInf()
The exposure range used:  -13.9826 11.52116 
The internal knots are:    (Empty means no internal knots used) 
Random-effect is considered for smoothing and the actual random effect squared value is:  1 
-13.9826 11.52116 -7.440576 
The actual basline value used: -7.4471 
Error in Smooth(RES, Norder = 3) : 
  please use the proper baseline value so it is inside the exposure range

thank you again!

**Comment by HDTian** [comment]
Hi, I have updated the package, now hopefully you can use Smooth() without errors.

**Comment by 1297069621** [comment]
Thank you so much! Now the Smooth() works well.

But, there is "coxph" option in "family_used", then how could I set Y?  Y=outcome*survival_time ?

Yours~

**Comment by HDTian** [comment]
Hi, your outcome Y with 'coxph' should be a survival object as returned by the Surv function

For example; Try:
```R
library(survival)
Surv(  c(4,3,1,1,2,2,3)  , c(1,1,1,0,1,1,0) )  #survival object
test<-data.frame(  Y=  Surv(  c(4,3,1,1,2,2,3)  , c(1,1,1,0,1,1,0) ) )  #set Y as the Survival  object 
```
