### ISSUE TITLE
Questions on the results

### ISSUE THREAD

**Issue by Howlonghowlong** [HDTian/DRMR#3]
Dear Tian, I am really appreciate your effort in this field. Now, I successfully run my code and generate results, but I still have some questions on them.
Codes are presented as following:
rdat <- Stratify(data_ABSI_validation_DRMR_allcause,seed=123)
RES <- getSummaryInf(rdat,family_used = 'binomial',covariate = T)

smooth_res1 <- Smooth(RES,StraMet = 'DR', Norder = 1,baseline = 0) # AIC:-29.76; BIC: -29.46
smooth_res2 <- Smooth(RES,StraMet = 'DR', Norder = 2,baseline = 0) # AIC:-35.20; BIC: -34.59
smooth_res3 <- Smooth(RES,StraMet = 'DR', Norder = 3,baseline = 0) # AIC:-33.20; BIC: -32.29

smooth_res1$hp
smooth_res1$p
Q1: How to selected the appropriate value of "Norder" in "Smooth" function? Should it based on the AIC or BIC of the model (smooth_res)
Q2: what is the difference between "smooth_res1$hp" and "smooth_res1$p".

I also obtained two figures. Figure 1 was generated from the code of "smooth_res2$hp". Figure 2 was generated from the code of "smooth_res2$p".
Figure 1:  
![image](https://github.com/user-attachments/assets/b8692ad2-61a3-4f10-bebc-8813efe564c6)
Figure 2:
![image](https://github.com/user-attachments/assets/fc408344-188c-4a71-a533-8d3aea34ff5d)
.
Q3: I fitted a logistic model using "family_used='binomial'". Why the figures just presented estimates in Y scale.
Q4: How to determine if the association between them is linear or non-linear.

I am looking forward for your response. Thank you so much!

**Comment by HDTian** [comment]
Hi, Thanks for your comments

Q1. _'Norder'_ is a value controlling how flexible your fitted curve (ie effect shape) can be. There are many ways to determine it - even relying on your domain knowledge. AIC/BIC given here is also for _'Norder'_ selection, so you can choose your _'Norder'_ by, say, choosing the smallest AIC or BIC value.

Q2. Both _'smooth_res1$hp'_ and _'smooth_res1$p'_ returns you the fitted curve (ie effect shape). _$hp_ returns you the original effect shape, while _$p_ returns you the **differentiated** effect shape. So technically, _$hp_ is the integral curve of _$p_. I personally prefer to use _$p_ as the differentiated effect shape plot directly reflects the effect size at the corresponding local exposure value point

Q3. Could you explain more about what the figures are and what the Y scale you mean here? 

Q4. The left upper corner of your _'smooth_res1$p_' figure provides two kinds of the tests on the effect shape. The null hypothesis is that the effect is linear, so any rejection (e.g. pvalue<0.05) should give you the evidence to conclude that the effect is nonlinear. You can choose any one of them, but typically, the trend test (at the second line) is of high power and may be recommended. So in your example provided, the p-value of the trend test is ~0.019, which gives you the evidence to support that the effect is nonlinear...

Hope they help!

**Comment by Howlonghowlong** [comment]
Really appreciate your prompt and valuable feedback.

Let me explain more about the Figure. This Figure (Figure 1) was obtained following the four-step codes:
(1) rdat <- Stratify(data_ABSI_validation_DRMR_allcause,seed=123)
(2) RES <- getSummaryInf(rdat,family_used = 'binomial',covariate = T)
(3) smooth_res2 <- Smooth(RES,StraMet = 'DR', Norder = 2,baseline = 0) 
(4) smooth_res2$p
Figure 1: 
![image](https://github.com/user-attachments/assets/ddd30206-2f8c-4cbc-8ed3-7ea34ea8f3f3)
In this analysis, the exposure is a continuous variable and the outcome is a binary variable. Typically, this association shoule be presented as OR (95%CI), while the y-axis in figure 1 represented LACE estimate (β).

Additionally, following the Q4, in my opinion, the solid line in Figure 2 represents the fitted curve across LACE estimates and the dashed line represents the confidence intervals. While the evidence suggests that this is a non-linear correlation (P=0.019), it seems that they are just positively correlated without a specific shape. When I run the following four-step codes, the figure 2 was obtained
(5) rdat <- Stratify(data_ABSI_validation_DRMR_allcause,seed=123)
(6) RES <- getSummaryInf(rdat,family_used = 'binomial',covariate = T)
(7) smooth_res1 <- Smooth(RES,StraMet = 'DR', Norder = 1,baseline = 0) 
(8) smooth_res1$p
Figure 2:
![image](https://github.com/user-attachments/assets/0a39dd09-e8f4-4483-906c-4ed469c6bd83)
The statistical evidence suggests that this is still a non-linear association (P=0.019), but how do I know if they are positively or negatively correlated?

**Comment by HDTian** [comment]
Hi,
Sorry for the late reply.

When your exposure is continuous and your outcome is binary and your model is the logistic model. The returned LACE estimate is targeted to the log odds ratio - so if you wish to interpret OR (and its 95% CI) you can simply adopt an exponential transformation to them.

The test regarding the effect linearity/nonlinearity is only based on the stratum-specific summary statistics rather than the smoothed curve, so do not worry if the test results are the same in both of your figures. In your example here, I would believe the effect shape is nonlinear (also indicated by the trend test) and when smoothing prefer using the second-order fitted curve (i.e. _Norder = 2_ in _Smooth_ function)

**Comment by Howlonghowlong** [comment]
Thanks a lot

**Comment by Howlonghowlong** [comment]
您发给我的信件已经收到。谢谢！The letter has been received! I'll reply soon. Thanks!
